### GSVA analysis Hugo paper

## Import data and transform to log CPM
# Import files are different from the ones imported in cBioPortal because to get the right results
# we needed the readcounts without RPKM transformation
expr_file = "CombineHtseqCount.PD1.May27.2016.PtID.txt"
sample_file = "SAMPLES.txt"
genesets_file = "msigdb.v6.0.symbols.gmt"

library(edgeR)  # edgeR is necassary to transform the counts to log cpm values

# Import data
dat <- read.delim(expr_file,sep="\t",header=T,row.names=1)
dge <- DGEList(counts=dat)
norm.factor <- calcNormFactors(dge)
dat.norm <- cpm(norm.factor, normalized.lib.sizes=TRUE, prior.count=2, log=TRUE)

# Import geneset file with gene symbols (maybe the transferal of symbol to entrez makes a change)
# From sanders script, the hugo gene sets
mapki_genesets_names <- c(
  "MAPKi_INDUCED_EMT",
  "MAPKi_INDUCED_ANGIOGENESIS",
  "EP_BLOOD_VESS_DEVEL_DN_IN_R",
  "PH_BLOOD_VESS_DEVEL_DN_IN_R",
  "EP_RESP_TO_WOUNDING_DN_IN_R",
  "PH_RESP_TO_WOUNDING_DN_IN_R",
  "MS_RESP_TO_WOUNDING_UP_IN_MAPKi_aPDL1_NR",
  "MS_RESP_TO_HYPOXIA_UP_IN_MAPKi_aPDL1_NR",
  "POST_OP_WOUNDHEALING",
  "HOEK_INVASIVE_SIG",
  "HOEK_PROLIFEATIVE_SIG",
  "MAPKR_BLOOD_VESS_DEVEL_UP",
  "DTPP_BLOOD_VESS_DEVEL_UP",
  "DTP_BLOOD_VESS_DEVEL_UP",
  "MAPKR_REG_CELL_PROLIF_UP",
  "DTPP_REG_CELL_PROLIF_UP",
  "DTPP_CELL_ADHESION_UP",
  "PLX2D_CELL_ADHESION_UP",
  "DTPP_RESP_TO_WOUNDING_UP"
)

mapki_genesets_genes <- c(
  "ADAM12,AURKA,BCAT1,BGN,CDH11,CENPF,CKS2,COL10A1,COL11A1,COL3A1,COL5A1,COL5A2,COL6A2,COL6A3,DTL,EPYC,FAP,FCGR1B,FN1,GREM1,IGHM,INHBA,KIF2C,LOXL2,LRRC15,MMP11,NCAPG,NID2,NUAK1,RRM2,SLC16A3,SULF1,TNFAIP6,VCAN",
  "ANPEP,BGN,BMP4,CDH5,COL3A1,CYR61,DLL4,EDN1,EMCN,ID1,KDR,NRP1,PLAU,PPAP2B,PROK2,PRRX2,RHOB,ROBO4,SOX17,SOX18,TGFB2,THBS1,THY1,VEGFA,VEGFC",
  "FGF9,PGF,S100A7,PDGFA,TNFRSF12A,EDN1,ANPEP,PRRX2,SRF,CDH5,TGFB2,SHB,HAND2,HMOX1,ROBO4,RHOB,IL1B,SOX18,SOX17,THBS1,ANGPT2,PPAP2B,CYR61,BMP4,KLF5,FLT1,JUNB,SLIT2,KDR,PROK2,VEGFC,BGN,MEOX2,EREG,ID1,JMJD6,DLL4,VEGFA",
  "EMCN,ACVRL1,LMO2,IL18,COL3A1,FGF10,ANPEP,ENPEP,PRRX2,GJA4,CXCL12,MMP2,CDH5,TGFB2,EDNRA,ACE,S1PR1,PTK2B,TDGF1,ROBO4,PLCD1,SOX18,SOX17,LOX,PPAP2B,COL18A1,BMP4,SELP,EPAS1,EGFL7,TGFBR2,COL15A1,TBX1,KDR,THY1,PROK2,BGN,ID1,PROK1,DLL4,PLXDC1,NOTCH4,ECSCR,COL1A2,ZFPM2,ATPIF1,ENG",
  "F2RL2,S100A8,PDGFB,PDGFA,F2RL1,S100A9,TLR2,CXCR1,CXCR2,IL11,TGFB2,CASP6,FOS,S1PR3,MYD88,LTB4R,HMOX1,SERPINE1,CCL3L3,IL1B,IRAK2,F11,IL18RAP,F10,PLAUR,PROK2,TNFAIP6,THBD,IL20RB,EREG,CARD18,SERPINB2,DSP,RIPK2,KDM6B,NGF,CXCL1,CCL3,CCL2,C9,CXCL3,DRD5,CXCL2,CCL8,BDKRB1,PF4,FPR2,CXCL6,TRIM72,CCL5,SRF,CCL7,TNFRSF1A,PCSK1,MEFV,CCL20,GP1BB,POU2F3,KLKB1,KRT1,CD24,THBS1,PTX3,KLK8,IL6,CEBPB,MAP2K3,S100A12,SOD2,CCL11,ITGA5,HBEGF,ID3,SELE,F2R",
  "F2RL3,ACVRL1,ADORA3,MASP1,TACR1,TGFB3,CXCR1,FGF10,CXCR2,MMRN1,TGFB2,CFHR1,CFP,CASP6,GP5,DYSF,AOAH,CCL3L3,CFH,MS4A2,LOX,LBP,CFD,XCR1,IL18RAP,PTGER3,CCL4L2,SERPING1,CDO1,MECOM,PROK2,SIGLEC1,CCR7,KLRG1,CD36,THBD,CD40LG,SERPINF2,PLA2G7,TFPI,AOC3,CYSLTR1,C6,COL3A1,C1R,PF4,GPR68,C1S,CCL5,IL23A,CCL23,MEFV,GP1BB,CNR2,NFATC4,NOX4,SELP,KL,EFEMP2,TGFBR2,IGF2,C4BPA,CCL16,CCL18,NOTCH3,VWF,ID3,ENG,SELE,IGFBP4,BMP6",
  "ADORA3,PDGFA,TLR2,ADORA1,TGFB1,IL10,CD97,S1PR3,GPX1,NLRC4,MYD88,CCL3L1,SERPINA3,CHST2,STXBP1,CCL4L2,SERPING1,CD40,GAL,PLAUR,C8G,ADM,CTSB,VSIG4,PLA2G2D,TPST1,GGCX,TF,CCL2,RTN4RL1,ADORA2A,CCL8,C1R,ITGB3,FPR2,TIMP3,TNFRSF4,CCL7,TNFRSF1A,SLC11A1,TNFRSF1B,GP1BB,IL10RB,RAC1,SCN9A,ENO3,C2,SCG2,FN1,SPP1,NOX4,PLAT,IL2RA,TNFSF4,STAT3,CCNB1,APOL2,CD55,TFRC,C1RL,SYT17",
  "TF,CCL2,FLT1,ACTN4,SOCS3,PDGFA,ALDOC,EGLN3,NR4A2,TGFB1,DDIT4,CD38,HYOU1,HSP90B1,PLOD1,TFRC,ADM,PLOD2,VEGFA,PSEN2,MT3,ANGPTL4",
  "MMP3,PPBP,CXCL5,PTX3,PTHLH,TDO2,SPINK6,SPP1,MMP10,IL8,MME,GREM1,CTSZ,CXCL6,THBS1,SCG5,TFPI2,PTGS2,CXCL1,IL1A,PCSK1,AREG,IL13RA2,KIAA1199,CCL18,FST,LILRB1,CTNNB1,CLC,CXCL3,CEACAM6,LILRB2,ITCH,S100A12,CCDC102B,GLIS3,MS4A6E,RARRES1,NRG1,PHLDA1,MS4A4A,HAS2,TFEC,CCR1,ANXA3,CR1,IL1RL1,ADAM12,CCNA1,PLA2G7,ENPEP,SPON1,INHBA,STEAP1,STEAP4,TMSB15A,FGF7,PI15,C8orf4,CYBB,MED18,IGSF6,SAA1,RGS13,DEFB4A,SLC16A3,CCL3,AQPEP,CYP1B1,FAM20A,DKK1,IKBIP,SULF1,PXDN,HMOX1,FMO3,SERPINA3,NAA15,MSR1,CCL8,TMEFF1,KLK6,C13orf33,TNFAIP6,MGST1,SRSF6,SRGN,IGF2BP3,PCSK5,LAMC2,OLFML2B,NCEH1,FABP4,IL6,C5AR1,ALDH1A3,PDPN,LYZ,CD163,RAB12,RGS18,HBB,TIMP1,CNN3,FAM83A,CYR61,TNC,DPYSL3,PRR16,BAG2,DSEL,LIPG,PLAC8,CXCL2,FCER1G,SUSD5,NEXN,KLHL6,LMNB1,GPRC5A,TCEAL7,FPR1,APOBEC3A,ITGB6,HS3ST1,GBP6,ITGB5,ADIPOQ,CPXM1,PKP2,NNMT,OLR1,PPP3R1,BUB1,BCL2A1,MAP9,GCLM,S100P,F3,TMPRSS11E,BEND6,FCGR3A,DDX3Y,PI3,MS4A7,FCN1,TLR4,UCHL1,CYTL1,ST8SIA4,MMP9,ALDH1L2,DEPDC1,RNASE2,SPINK7",
  "ADAM12,AMOTL2,AXL,BIRC3,CDH13,CDK14,COL13A1,CRIM1,CRISPLD2,CYR61,DPYD,EFEMP1,EGFR,F2RL1,FGF2,FLNB,FOXD1,FST,FZD2,HEG1,HS3ST3A1,ITGA2,ITGA3,KCNMA1,LOXL2,MYOF,NRP1,NTM,NUAK1,OSMR,PDGFC,PODXL,S100A2,SLC22A4,SLIT2,SYNJ2,TCF4,THBS1,TLE4,TNFRSF11B,TPBG,TPM1,TRAM2,WNT5A,ZEB1",
  "ACP5,ADCY2,APOE,ASAH1,BIRC7,C21orf91,CAPN3,CDH1,CDK2,CDK5R1,CEACAM1,DAPK1,DCT,FAM174B,GALNT3,GNPTAB,GPM6B,GPR143,GPRC5B,GYG2,HPS4,INPP4B,IRF4,IVNS1ABP,KAZ,MBP,MICAL1,MITF,MLANA,MYO1D,NR4A3,OCA2,PHACTR1,PIR,PLXNC1,PMEL,RAB27A,RAB38,RGS20,RHOQ,RRAGD,SEMA6A,SIRPA,SLC45A2,ST3GAL6,STX7,TNFRSF14,TRPM1,TYR,TYRP1,WDR91,ZFYVE16",
  "CAV1,NRP1,EPAS1,COL3A1,EDN1,COL5A1,CITED2,CDH13,VEGFC,S1PR1,JUN,CCBE1,PLCD3,FOXC2,COL1A1,FGF2,PLAU,CYR61",
  "CAV1,NRP1,LMO2,EDN1,COL3A1,MMP2,CXCL12,CITED2,AGT,CCBE1,PLCD3,RHOB,SEMA3C,THBS1,FGF2,CEACAM1,SCG2,CYR61,BMP4,COL18A1,EPAS1,MMP19,MYH9,ARHGAP24,COL5A1,THY1,CDH13,VEGFC,BGN,EPGN,JUN,VEGFA,NTRK2,COL1A2,COL1A1,PLAU",
  "CAV1,NRP1,LMO2,EDN1,COL3A1,TNFSF12,MMP2,CITED2,ANGPTL6,CXCR4,PLCD3,RHOB,QKI,SEMA3C,THBS1,CYR61,KLF5,COL18A1,EPAS1,MMP19,MYH9,ARHGAP24,COL5A1,ANXA2,THY1,SMO,CDH13,BGN,JUN,NTRK2,COL1A2,COL1A1,PLAU",
  "CAV2,RBP4,CAV1,FOSL2,CCL2,NRP1,IGFBP7,CLU,EDN1,NFKBIA,IL15,IL34,SOX9,S1PR3,AGTR1,BDNF,S1PR1,SPEG,HLX,SERPINE1,NKX3-1,PDGFC,CD24,NRG1,RUNX2,FGF2,EGFR,PTGER2,TP53I11,IL6,IRS1,PDCD1LG2,MXD4,VEGFC,CDH13,TNFRSF9,ADRB2,JUN,F3,BNC1,IL12A,PDGFRB,TGFB1I1,PLAU,NGF",
  "RARRES3,FOSL2,FGF7,NRP1,PDGFB,FGF17,IGFBP7,EDN1,GJA1,FOXO4,CXADR,VIPR1,GLI3,IL31RA,AZGP1,AGTR1,WISP2,BDNF,GPC3,HLX,SERPINE1,PDGFC,NRG1,FGF2,EBI3,EGFR,PRKCA,PTPRK,PTGER2,CD40,IRS1,PDCD1LG2,MXD4,MYCN,TNS3,VEGFC,ADRB2,ADAMTS8,CCND2,CHRM1,F3,JUN,BTG4,GRN,VEGFA,IL12A,PDGFRB,NGFR,TGFB1I1,PMP22,NGF,CAV2,CAV1,CCL2,IFITM1,CLU,PTH1R,NFKBIA,KIT,BDKRB2,IL34,TIMP2,SOX9,ADA,VDR,IL12RB1,SPEG,AGT,ADRA2A,NKX3-1, CD24,THBS1,PPAP2A,RUNX2,SCG2,BMP4,COL18A1,IL6,TP53I11,TNFSF4,KAT2B,HCLS1,KLF11,TAX1BP3,CDH13,ATF3,NUPR1,EPGN,ETS1,DLX5,BNC1,FABP4,NR5A2,PLAU,KCTD11,F2R",
  "CADM3,NRP1,THRA,CADM1,TLN2,IGFBP7,NPNT,FERMT2,BCAM,L1CAM,EDIL3,CXADR,CXCL12,VCL,NRCAM,AZGP1,WISP2,TGFBI,RHOB,LOXL2,NEGR1,BOC,CEACAM1,CDH24,CYR61,SPON1,EGFR,F11R,PTPRK,PCDHB7,NRXN2,CNTN6,SDK1,CPXM2,MYH9,THY1,JUP,CD36,CLDN1,LAMC2,TGFB1I1,PARVA,ACHE,CCL2,COL3A1,ITGA11,COL28A1,SPOCK1,IL32,CDH3,PCDHB11,SOX9,APLP1,ALCAM,COL17A1,LAMB2,SORBS1,FAT4,AGT,TTYH1,COL6A3,MSLN,CD24,THBS1,SELPLG,THBS3,APBA1,NPHP1,FN1,COL18A1,FLRT1,BGLAP,BMP1,COL13A1,ITGA1,NFASC,HSPG2,CELSR2,NID2,PCDH17,COL5A3,COL16A1,COL5A1,COL4A6,CDH13,ERBB2IP,ITGA5,PKP3,ADAM22,NTM,FEZ1",
  "THRA,TLN2,FERMT2,L1CAM,BCAM,EDIL3,VCL,AZGP1,WISP2,RHOB,LOXL2,COL11A1,CYR61,PCDHB5,CNTN6,MYH9,JUP,NCAM2,CD36,CD99L2,TGFB1I1,PARVA,COL3A1,PCDHB15,NINJ1,PCDHB11,PKD1L1,CLDN14,ALCAM,SORBS1,ROPN1B,TTYH1,PVRL2,MSLN,ACAN,CD24,THBS1,GPNMB,APBA1,THBS3,COL18A1,MAG,FLRT1,ADAM23,ITGA1,HSPG2,CELSR3,NID2,PCDH17,COL16A1,COL5A3,PCDH18,COL14A1,FREM2,CDH19,CYFIP2,ANTXR1,ABL2",
  "F2RL2,NRP1,FGF7,PDGFB,F2RL1,TLR3,DYSF,SERPINE1,CFH,NRG1,FGF2,IRAK2,F11R,LY96,CD40,SDC1,CD36,F3,TFPI,NGFR,NGF,ACHE,CCL2,RTN4RL1,C3,CXCL3,COL3A1,CXCL2,CLU,C1R,BDKRB2,C1S,CDH3,MDK,TPM1,CCL26,IGSF10,LAMB2,NFATC4,CD24,THBS1,FN1,SCG2,IL6,TNFSF4,EFEMP2,MSTN,COL5A1,APOL3,PLSCR4,NUPR1,ITGA5,CD59,AOX1,PLA2G4C,HDAC9,PLAU,IGFBP4,F2R"
)
mapki_genesets_genes_list<- strsplit(mapki_genesets_genes, ",")

names(mapki_genesets_genes_list) <- mapki_genesets_names

library(qusage)
msigdb_symbol_genesets <- read.gmt(genesets_file)

# Append genesets together
genesets_all <- c(mapki_genesets_genes_list, msigdb_symbol_genesets)

# Perform GSVA analysis
# bootstrap values are not used in the further analysis
library(GSVA)
library(snow)
gsva_result <- gsva(dat.norm, genesets_all, min.sz=10, max.sz=500, method="gsva", rnaseq=TRUE, no.bootstrap=2, parallel.sz=2, parallel.type="SOCK", mx.diff=TRUE)
gsva_scores <- data.frame("geneset_id" = rownames(gsva_result$es.obs), gsva_result$es.obs, check.names = F)
gsva_bootstrap <- data.frame("geneset_id" = rownames(gsva_result$bootstrap$p.vals.sign),gsva_result$bootstrap$p.vals.sign, check.names = F)

# Grab scores from genesets from figure and separate in two groups
genesets_figure <- c("JAEGER_METASTASIS_UP","MAPKi_INDUCED_EMT","LEF1_UP.V1_UP","POOLA_INVASIVE_BREAST_CANCER_UP","YE_METASTATIC_LIVER_CANCER","CHARAFE_BREAST_CANCER_BASAL_VS_MESENCHYMAL_UP","MAHADEVAN_GIST_MORPHOLOGICAL_SWITCH","VECCHI_GASTRIC_CANCER_ADVANCED_VS_EARLY_UP","LIEN_BREAST_CARCINOMA_METAPLASTIC","LU_TUMOR_ENDOTHELIAL_MARKERS_UP","LU_TUMOR_VASCULATURE_UP","LU_TUMOR_ANGIOGENESIS_UP","ROY_WOUND_BLOOD_VESSEL_UP","MAPKi_INDUCED_ANGIOGENESIS","EP_BLOOD_VESS_DEVEL_DN_IN_R","WESTON_VEGFA_TARGETS_12HR","WESTON_VEGFA_TARGETS_6HR","MAINA_VHL_TARGETS_DN","MS_RESP_TO_HYPOXIA_UP_IN_MAPKi_aPDL1_NR","HARRIS_HYPOXIA","KARAKAS_TGFB1_SIGNALING","JEON_SMAD6_TARGETS_DN","POST_OP_WOUNDHEALING","MISHRA_CARCINOMA_ASSOCIATED_FIBROBLAST_UP","MS_RESP_TO_WOUNDING_UP_IN_MAPKi_aPDL1_NR","DER_IFN_GAMMA_RESPONSE_UP","DER_IFN_ALPHA_RESPONSE_UP","DER_IFN_BETA_RESPONSE_UP","GRANDVAUX_IFN_RESPONSE_NOT_VIA_IRF3","ZHANG_INTERFERON_RESPONSE","NATSUME_RESPONSE_TO_INTERFERON_BETA_UP","RADAEVA_RESPONSE_TO_IFNA1_UP","HECKER_IFNB1_TARGETS")
gsva_scores_figure <- gsva_scores[genesets_figure,-1]
gsva_scores_figure <- gsva_scores_nornaseq[genesets_figure,-1]

group_info <- read.table(sample_file, sep="\t", header=FALSE, row.names=1)
responders <- rownames(group_info)[which(group_info[,1] == "R")]
nonresponders <- rownames(group_info)[which(group_info[,1] == "NR")]

gsva_score_responders <- gsva_scores_figure[,responders]
gsva_score_nonresponders <- gsva_scores_figure[,nonresponders]

# Calculate Zscore to create the same figure
zscore_gsva <- t(apply(gsva_scores_figure, 1, function(x) ((x-mean(x)) / sd(x))))

zscore_responders <- zscore_gsva[,responders]
zscore_nonresponders <- zscore_gsva[,nonresponders]

dup_gsva <- rbind(cbind(gsva_score_nonresponders, gsva_score_responders), c(rep("non_responding", 13), rep("responding", 15)))
zscore_matrix_sort <- dup_zscore_matrix[,order(dup_zscore_matrix[34,], dup_zscore_matrix[1,])]
zscore_matrix <- zscore_gsva[,colnames(zscore_matrix_sort)]

library("RColorBrewer")
library("gplots")
hmcols<-colorRampPalette(c("blue","white","red"))

zscore_nonresponders <- zscore_nonresponders[,order(colnames(zscore_nonresponders), decreasing=TRUE)]
zscore_responders <- zscore_responders[,order(colnames(zscore_responders), decreasing=TRUE)]
all <- cbind(as.matrix(zscore_nonresponders), as.matrix(zscore_responders))
colnames(all) <- strsplit(as.character(colnames(all)), '.PD1')
response <- c(rep("non_responding", 13), rep("responding", 15))

heatmap.2(all, dendrogram="none", trace="none", Rowv=FALSE, Colv=FALSE, ColSideColors= c(ifelse(response == "non_responding", "black", "gray")), col=hmcols, keysize=1, density.info="none", key.xlab="Row Z-score", margins=c(15,30))

## Data to create supplemental table (was not certain if authors calculated median or mean,
## so calculated both)
median_responders <- apply(gsva_score_responders, 1, median)
median_nonresponders <- apply(gsva_score_nonresponders, 1, median)
diff_median <- median_responders - median_nonresponders

mean_responders <- apply(gsva_score_responders, 1, mean)
mean_nonresponders <- apply(gsva_score_nonresponders, 1, mean)
diff_mean <- mean_responders - mean_nonresponders

supl_table <- data.frame(diff_median, median_nonresponders, median_responders)
rownames(supl_table) <- genesets_figure
supl_table_mean <- data.frame(diff_mean, mean_nonresponders, mean_responders)
rownames(supl_table_mean) <- genesets_figure